language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false
cache: cargo
before_script: rustup add rustfmt-preview
script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose --features ci
notifications:
  email:
    on_success: never
